### ISSUE TITLE
Doesn't work with Pulumi 1.0.0

### ISSUE THREAD

**Issue by davidolmo** [gmiretti/pulumi-aws-py-lambda-api-gateway#1]
Thanks for sharing this! It helped me a lot. Getting into Pulumi is being difficult

I've tried executing it on Pulumi 1.0.0 and it doesn't work. The "pulumi up" command works perfectly, but there is something with lambda permissions that fails:

![image](https://user-images.githubusercontent.com/33136768/64723891-a7348080-d4d1-11e9-910f-713ca5585964.png)

![image](https://user-images.githubusercontent.com/33136768/64723959-c9c69980-d4d1-11e9-8d7e-769294965818.png)

**Comment by gmiretti** [comment]
Ok, I'll test with pulumi 1.0, I developed it with pulumi 0.16.3 and I didn't have on CI

**Comment by gmiretti** [comment]
I unfixed the libs in requeriments.txt, so I tested it with pulumi-1.0.0 and pulumi-aws-1.1.0 libs and it worked. Could you try it with this libs?

**Comment by davidolmo** [comment]
Thanks for answering so fast!
Wow, you're right it works from the browser/curl. I hadn't even tried it before, as running the test from AWS Gateway GUI throws the "invalid permissions error", and the lambda GUI prompts that second screenshot error (the errors are still appearing on AWS, but the code works). There is probably something I'm not understanding about how AWS works even with those errors...

**Comment by gmiretti** [comment]
Yeah, the TEST in the GUI it looks like doesn't work well with proxy integrations to lambda. 
You must call https://endpoint/stage-name to get the function content.
Happy to help!
If you are getting started with AWS lambda + API gateway in Python I'll recommend you to start using https://github.com/aws/chalice
